---
abstract: ~
author:
  - 'Peter Valdemar Mørch <peter@morch.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.84
  Module::Install: 0.01
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Number-Prefix
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/pmorch/perl-Number-Prefix
version: 0.1
